[package]
name = "nannou_playground"
version = "0.1.0"
authors = ["Stuart <stuart.lynn@gmail.com>"]
edition = "2018"

[dependencies]
nannou = "0.9"
geo = "0.12.0"
geo-types = "0.4.0"
geojson = { version =  "0.16.0", features=["geo-types"] }
serde_json = "1.0.39"
rayon = "1.0.3"